### PR TITLE
fixed your dumb stupid code

### PR DESCRIPTION
**Pull request by dazziedez**
using a reminder instead of asyncio.sleep. whaat???? ASYncio.sleep??? lol

### CODE REVIEW

**Comment by razyness** [comment]
:(

**Comment by razyness** [comment]
i didn't mean to maybe close it

**Comment by adonis1874** [comment]
you should apologize right now i think

**Comment by RegorForgot** [comment]
don't tell razy what to do

**Comment by adonis1874** [comment]
i meant enoki... so rude to razy for no reason!!!

**Pull request merged**
